import argparse
from amcrest import AmcrestCamera
from typing import Protocol, Optional, Any
from amcrest2mqtt.core import Amcrest2Mqtt

# grep -ERh --exclude interface.py 'def\s+[^_]' src/ | sed -E "s/^[[:space:]]+//g" | awk '{ print "   ", $0, "..." }' | sort


class AmcrestServiceProtocol(Protocol):
    """Common interface so mixins can type-hint against the full service."""

    async def build_camera(self: Amcrest2Mqtt, device: str) -> str: ...
    async def build_component(self: Amcrest2Mqtt, device: dict) -> str: ...
    async def check_event_queue_loop(self: Amcrest2Mqtt): ...
    async def check_for_events(self: Amcrest2Mqtt) -> None: ...
    async def collect_all_device_events(self: Amcrest2Mqtt) -> None: ...
    async def collect_all_device_snapshots(self: Amcrest2Mqtt) -> None: ...
    async def collect_events_loop(self: Amcrest2Mqtt): ...
    async def collect_snapshots_loop(self: Amcrest2Mqtt): ...
    async def connect_to_devices(self: Amcrest2Mqtt) -> dict[str, Any]: ...
    async def device_loop(self: Amcrest2Mqtt): ...
    async def get_events_from_device(self, device_id: str) -> None: ...
    async def get_snapshot_from_device(self, device_id: str) -> str | None: ...
    async def main_loop(self: Amcrest2Mqtt): ...
    async def process_device_event(self, device_id: str, code: str, payload: Any): ...
    async def refresh_all_devices(self: Amcrest2Mqtt): ...
    async def setup_device_list(self: Amcrest2Mqtt) -> None: ...
    def build_device_states(self: Amcrest2Mqtt, device_id: str) -> None: ...
    def build_parser() -> argparse.ArgumentParser: ...
    def classify_device(self: Amcrest2Mqtt, device: str) -> str: ...
    def get_api_calls(self: Amcrest2Mqtt): ...
    def get_attribute_topic(self: Amcrest2Mqtt, device_id, category, item, attribute) -> str: ...
    def get_availability_topic(self: Amcrest2Mqtt, device_id, category="availability", item=None) -> str: ...
    def get_camera(self, host: str) -> AmcrestCamera: ...
    def get_command_topic(self: Amcrest2Mqtt, device_id, category, item=None, command="set") -> str: ...
    def get_component_type(self: Amcrest2Mqtt, device_id): ...
    def get_component(self: Amcrest2Mqtt, device_id): ...
    def get_device_availability_topic(self: Amcrest2Mqtt, device_id): ...
    def get_device_block(self: Amcrest2Mqtt, id, name, vendor="Amcrest", sku=None): ...
    def get_device_name(self: Amcrest2Mqtt, device_id): ...
    def get_device_slug(self: Amcrest2Mqtt, device_id: str, type: Optional[str] = None) -> str: ...
    def get_device_state_topic(self: "Amcrest2Mqtt", device_id, mode_name=None): ...
    def get_device_topic(self: Amcrest2Mqtt, component_type, device_id, *parts) -> str: ...
    def get_device(self, host: str, device_name: str) -> None: ...
    def get_discovery_topic(self: Amcrest2Mqtt, component, item) -> str: ...
    def get_ip_address(self: Amcrest2Mqtt, string: str) -> str: ...
    def get_last_call_date(self: Amcrest2Mqtt): ...
    def get_last_update(self: "Amcrest2Mqtt", device_id: str) -> str: ...
    def get_mode(self: "Amcrest2Mqtt", device_id, mode_name): ...
    def get_modes(self: "Amcrest2Mqtt", device_id): ...
    def get_motion_detection(self, device_id: str) -> bool: ...
    def get_new_client_id(self: Amcrest2Mqtt): ...
    def get_next_event(self: Amcrest2Mqtt) -> str | None: ...
    def get_privacy_mode(self, device_id: str) -> bool: ...
    def get_recorded_file(self, device_id: str, file: str) -> str | None: ...
    def get_service_device(self: Amcrest2Mqtt): ...
    def get_service_topic(self: Amcrest2Mqtt, topic): ...
    def get_snapshot(self, device_id: str) -> str | None: ...
    def get_state_topic(self: Amcrest2Mqtt, device_id, category, item=None) -> str: ...
    def get_storage_stats(self, device_id: str) -> dict[str, str]: ...
    def get_vendor_device_slug(self: Amcrest2Mqtt, device_id): ...
    def handle_device_command(self: Amcrest2Mqtt, device_id: str, handler: str, message: str) -> None: ...
    def handle_service_command(self: Amcrest2Mqtt, handler: str, message: str) -> None: ...
    def is_discovered(self: "Amcrest2Mqtt", device_id: str) -> bool: ...
    def is_ipv4(self: Amcrest2Mqtt, string: str) -> bool: ...
    def is_rate_limited(self: Amcrest2Mqtt): ...
    def load_config(self: Amcrest2Mqtt, config_arg: str = None, media_arg: str = None) -> list[str, Any]: ...
    def main(argv=None): ...
    def mqtt_on_connect(self: Amcrest2Mqtt, client, userdata, flags, reason_code, properties): ...
    def mqtt_on_disconnect(self: Amcrest2Mqtt, client, userdata, flags, reason_code, properties): ...
    def mqtt_on_log(self: Amcrest2Mqtt, client, userdata, paho_log_level, msg): ...
    def mqtt_on_message(self: Amcrest2Mqtt, client, userdata, msg): ...
    def mqtt_on_subscribe(self: Amcrest2Mqtt, client, userdata, mid, reason_code_list, properties): ...
    def mqtt_safe_publish(self: Amcrest2Mqtt, topic, payload, **kwargs): ...
    def mqttc_create(self: Amcrest2Mqtt): ...
    def publish_device_availability(self: Amcrest2Mqtt, device_id, online: bool = True): ...
    def publish_device_discovery(self: Amcrest2Mqtt, device_id: str) -> None: ...
    def publish_device_state(self: Amcrest2Mqtt, device_id: str) -> None: ...
    def publish_service_availability(self: Amcrest2Mqtt): ...
    def publish_service_discovery(self: Amcrest2Mqtt): ...
    def publish_service_state(self: Amcrest2Mqtt): ...
    def read_file(self: Amcrest2Mqtt, file_name: str) -> str: ...
    def rediscover_all(self: Amcrest2Mqtt): ...
    def safe_split_device(self: Amcrest2Mqtt, topic, segment): ...
    def set_motion_detection(self, device_id: str, switch: bool) -> str: ...
    def set_privacy_mode(self, device_id: str, switch: bool) -> str: ...
    def to_gb(self: Amcrest2Mqtt, total: [int]) -> str: ...
    def upsert_device(self: Amcrest2Mqtt, device_id: str, **kwargs: dict[str, Any] | str | int | bool) -> None: ...
    def upsert_state(self: Amcrest2Mqtt, device_id, **kwargs: dict[str, Any] | str | int | bool) -> None: ...
